SELECT  
    CTA.AAC_IDENAAC AS NRO,
    SRV.ASE_IPPRIVADA AS SERVIDOR,
    CTA.ADM_IDPROY AS BD,
    LOWER(USR.TXT_ACC) AS USR,
    CONVERT(VARCHAR(10), CTA.ACC_FECHAFIN, 120) + ' ' + CTA.ACC_HORAFIN AS FFIN,
    CONVERT(VARCHAR(16), CTA.USU_SEG_FECHAINS, 120) AS FREG,
    CTA.AGE_SEG_CODIGO AS COD_USER,
    CTA.ESTADO,
    CTA.AAC_PERSMISO AS PERMISO,

    CASE WHEN LOWER(CTA.AAC_PERSMISO) LIKE '%rdp admin%' THEN 1 ELSE 0 END AS ADM,
    CASE WHEN LOWER(CTA.AAC_PERSMISO) LIKE '%rdp%' THEN 1 ELSE 0 END AS RDP,

    CASE WHEN LOWER(CTA.AAC_PERSMISO) LIKE '%sql%' THEN 1 ELSE 0 END AS SQL,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% r %' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rw%' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w%' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rwsp%' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w, sp%'
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rw sp%' THEN 1 ELSE 0 END AS r,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% w %' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rw%' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w%' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rwsp%' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w, sp%'
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rw sp%' THEN 1 ELSE 0 END AS w,

    CASE WHEN (LOWER( CTA.AAC_PERSMISO ) LIKE '% rw %' 
           OR LOWER(CTA.AAC_PERSMISO) LIKE '%r/w%')
           AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rwsp%' 
           AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rw sp%'
           AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w, sp%' 
           AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w sp%' THEN 1 ELSE 0 END AS rw,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% sp %' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rwsp%' 
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%rw sp%'
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w, sp%'
         AND LOWER(CTA.AAC_PERSMISO) NOT LIKE '%r/w sp%' THEN 1 ELSE 0 END AS sp,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% rw sp %' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% rwsp %' 
       OR LOWER(CTA.AAC_PERSMISO) LIKE '%r/w, sp%'
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% r/w sp %' THEN 1 ELSE 0 END AS rwsp,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% sp upd%' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% sm %' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% sp modif%' THEN 1 ELSE 0 END AS sm,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% rw sp upd%' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% rwsp upd %' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% rwsm %' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% rwsp modif %' THEN 1 ELSE 0 END AS rwsm,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% job%' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% jobs%' THEN 1 ELSE 0 END AS job,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% sysadmin %' THEN 1 ELSE 0 END AS sysad,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% prf %' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% profil %'
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '%trace%' THEN 1 ELSE 0 END AS prf,

    CASE WHEN LOWER( CTA.AAC_PERSMISO ) LIKE '% owner %' 
       OR LOWER( CTA.AAC_PERSMISO ) LIKE '% propietario %' THEN 1 ELSE 0 END AS own,

    CASE WHEN LOWER(CTA.AAC_PERSMISO) LIKE '%rdp%' THEN
           CASE WHEN SRV.ASE_IPPRIVADA IN 
                 ('10.0.0.49','10.0.0.56','10.0.0.48','10.0.0.203',
                  '10.0.0.61','10.0.0.77','10.0.0.201')
                  THEN 'FIDENSLAT\' ELSE '.\' END
         ELSE '' END AS DOMINIO
FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA CTA
JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.AGE_SEG_CODIGO = USR.COD_USER AND USR.STATUS=1
JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE = SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
WHERE CTA.ACC_FECHAFIN >= CAST(GETDATE() AS date)
  AND CTA.ESTADO IN (1,2)
ORDER BY LOWER(USR.TXT_ACC) ASC, CTA.AAC_IDENAAC ASC