SELECT * FROM ACCOUNT;
SELECT * FROM ACCOUNT_ROL;


SELECT * FROM ProyFidens.dbo.SYS_ACCOUNT WHERE TXT_ACC = 'cberruz'
SELECT * FROM ProyFidens.dbo.SYS_ACCOUNT WHERE TXT_ACC = 'mlizama'	-- COD_USER
SELECT * FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA WHERE AAC_IDENAAC = 16706
SELECT * FROM ProyFidens.dbo.TB_SEG_AGENTES WHERE AGE_SEG_CODIGO = '00053'
SELECT * FROM ProyFidens.dbo.TB_SEG_AGENTES WHERE AGE_SEG_CODIGO = '00108'
SELECT * FROM ProyFidens.dbo.SYS_ACCOUNT WHERE COD_ACC = 108

SELECT * FROM ProyFidens.dbo.ADM_SERVIDOR

SELECT *
FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA CTA
INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.AGE_SEG_CODIGO = USR.COD_USER
INNER JOIN ProyFidens.dbo.TB_SEG_AGENTES AGE ON USR.COD_USER = AGE.AGE_SEG_CODIGO
INNER JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE=SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
--WHERE CTA.AAC_IDENAAC = 16706
WHERE CTA.ACC_FECHAFIN <= CAST(GETDATE() AS date)
AND CTA.ESTADO IN (1,2)
AND CTA.AAC_IDENAAC=16706
ORDER BY CTA.USU_SEG_FECHAINS ASC;

SELECT * FROM ProyFidens.dbo.TB_SEG_AGENTES


SELECT CTA.AAC_IDENAAC AS NRO, CTA.USU_SEG_USUARIOINS AS CODUSR, CTA.ASE_IDENASE AS SERV, CTA.ADM_IDPROY AS PRY, 
  CTA.AAC_PERSMISO AS SOLIC, CTA.AAC_DESC_ACTIVIDAD AS DESCRIBE, 
  CONVERT(VARCHAR(16), CTA.AAC_FECHAINICIO, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAINICIO, 108) AS FINI,
  CONVERT(VARCHAR(16), CTA.ACC_FECHAFIN, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAFIN, 108) AS FFIN,  
  CTA.ESTADO AS ESTADO, CTA.USU_SEG_FECHAINS AS FREG,
  LOWER(USR.TXT_ACC) AS USR, USR.COD_ACC AS CODACTIVO,
  SRV.ASE_IPPRIVADA AS IP_PRIV, SRV.ASE_IPPULICA AS IP_PUB, SRV.ADM_IDPROY AS PRYSRV,
  CTA.AGE_SEG_CODIGO AS COD_USER
	FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA
	-- INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.AGE_SEG_CODIGO=USR.COD_USER 
	-- INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.USU_SEG_USUARIOINS=USR.COD_USER AND USR.STATUS=1
	INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.AGE_SEG_CODIGO=USR.COD_USER -- AND USR.STATUS=1
	-- INNER JOIN ProyFidens.dbo.TB_SEG_AGENTES USR2 ON CTA.AGE_SEG_CODIGO=USR2.AGE_SEG_CODIGO -- AND USR.STATUS=1
	INNER JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE=SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
	WHERE -- CTA.AAC_FECHAINICIO = CAST(GETDATE() AS date) 
	-- CTA.AAC_FECHAINICIO BETWEEN '2026-02-23' AND '2026-02-24'
	CTA.ACC_FECHAFIN >= CAST(GETDATE() AS date)
	AND CTA.ESTADO IN (1,2,3)
	AND AAC_IDENAAC = 16706
	ORDER BY CTA.USU_SEG_FECHAINS ASC;


SELECT CTA.AAC_IDENAAC AS NRO, CTA.USU_SEG_USUARIOINS AS CODUSR, CTA.ASE_IDENASE AS SERV, CTA.ADM_IDPROY AS PRY, 
  CTA.AAC_PERSMISO AS SOLIC, CTA.AAC_DESC_ACTIVIDAD AS DESCRIBE, 
  CONVERT(VARCHAR(16), CTA.AAC_FECHAINICIO, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAINICIO, 108) AS FINI,
  CONVERT(VARCHAR(16), CTA.ACC_FECHAFIN, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAFIN, 108) AS FFIN,  
  CTA.ESTADO AS ESTADO, CTA.USU_SEG_FECHAINS AS FREG,
  LOWER(USR.TXT_ACC) AS USR, USR.COD_ACC AS CODACTIVO,
  SRV.ASE_IPPRIVADA AS IP_PRIV, SRV.ASE_IPPULICA AS IP_PUB, SRV.ADM_IDPROY AS PRYSRV,
  AGE_SEG_CODIGO AS COD_USER
	FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA
	INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.USU_SEG_USUARIOINS=USR.COD_USER AND USR.STATUS=1
	INNER JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE=SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
	WHERE CTA.AAC_FECHAINICIO = '2026-02-20'
	-- CTA.AAC_FECHAINICIO = CAST(GETDATE() AS date) 
	AND CTA.ESTADO IN (2,6)
	AND (CTA.AAC_PERSMISO LIKE '%SQL%' OR CTA.AAC_PERSMISO LIKE '%RDP%')
	ORDER BY CTA.USU_SEG_FECHAINS ASC;

SELECT CTA.AAC_IDENAAC AS NRO, CTA.USU_SEG_USUARIOINS AS CODUSR, CTA.ASE_IDENASE AS SERV, CTA.ADM_IDPROY AS PRY, 
  CTA.AAC_PERSMISO AS SOLIC, CTA.AAC_DESC_ACTIVIDAD AS DESCRIBE, 
  CONVERT(VARCHAR(16), CTA.AAC_FECHAINICIO, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAINICIO, 108) AS FINI,
  CONVERT(VARCHAR(16), CTA.ACC_FECHAFIN, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAFIN, 108) AS FFIN,  
  CTA.ESTADO AS ESTADO, CTA.USU_SEG_FECHAINS AS FREG,
  LOWER(USR.TXT_ACC) AS USR, USR.COD_ACC AS CODACTIVO,
  SRV.ASE_IPPRIVADA AS IP_PRIV, SRV.ASE_IPPULICA AS IP_PUB, SRV.ADM_IDPROY AS PRYSRV,
  AGE_SEG_CODIGO AS COD_USER
	FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA
	INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.USU_SEG_USUARIOINS=USR.COD_USER AND USR.STATUS=1
	INNER JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE=SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
	WHERE CTA.AAC_FECHAINICIO = CAST(GETDATE() AS date) AND CTA.ESTADO IN (1,2,6)
	AND (CTA.AAC_PERSMISO LIKE '%SQL%' OR CTA.AAC_PERSMISO LIKE '%RDP%')
	AND LOWER(USR.TXT_ACC) = 'mlizama' 
	AND SRV.ASE_IPPRIVADA = '10.0.0.102'
	ORDER BY CTA.USU_SEG_FECHAINS ASC;

SELECT *
FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA
WHERE CTA.AAC_FECHAINICIO = CAST(GETDATE() AS date)

SELECT TOP(100) COD_USER AS CODUSR, TXT_ACC AS USR, COD_ACC
	FROM SYS_ACCOUNT 
	WHERE STATUS=1 
	ORDER BY COD_USER;

SELECT ASE_IDENASE AS SERV, ASE_IPPRIVADA AS IP_PRIV, ASE_IPPULICA AS IP_PUB, ADM_IDPROY AS PRY
	FROM ADM_SERVIDOR 
	WHERE ASE_ESTADO=1;
	-- AND ASE_IDENASE=36;

--ORDER BY USU_SEG_FECHAINS DESC;

SELECT TOP(100) * FROM SYS_LOGSESSION;