-- EXEC master.dbo.rdu_infraProyFidensSolicitadosRDU '.\gchavez', '10.0.0.102', 'RDP', NULL;
/*
			SELECT CTA.AAC_IDENAAC AS NRO, CONVERT(VARCHAR(16), CTA.ACC_FECHAFIN, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAFIN, 108) AS FFIN,
			CONVERT(VARCHAR(16), CTA.AAC_FECHAINICIO, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAINICIO, 108) AS FINI,
			AGE_SEG_CODIGO AS COD_USER
				FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA
				INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.USU_SEG_USUARIOINS=USR.COD_USER AND USR.STATUS=1
				INNER JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE=SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
				WHERE CTA.ACC_FECHAFIN >= CAST(GETDATE() AS date) 
				-- CTA.AAC_FECHAINICIO = CAST(GETDATE() AS date) 
				AND CTA.ESTADO IN (1,2)
				AND CTA.AAC_PERSMISO LIKE '%RDP%'
				AND SRV.ASE_IPPRIVADA = '10.0.0.201'
				AND LOWER(USR.TXT_ACC) = 'cberruz';

			SELECT TOP 20 CTA.*, USR.* FROM 
			ProyFidens.dbo.ADM_ACTIVACION_CUENTA CTA 
			INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.AGE_SEG_CODIGO=USR.COD_USER AND USR.STATUS=1
			ORDER BY CTA.AAC_IDENAAC DESC;
				
			SELECT * FROM ProyFidens.dbo.SYS_ACCOUNT WHERE COD_USER=110
			UPDATE ProyFidens.dbo.SYS_ACCOUNT SET TXT_ACC='hcaycho' WHERE COD_USER=110
*/

USE [master]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('dbo.rdu_infraProyFidensSolicitadosRDU') IS NOT NULL
    DROP PROCEDURE dbo.rdu_infraProyFidensSolicitadosRDU;
GO
-- =============================================
-- Author:		Leonel
-- Create date: 2026-02-20
-- Description:	Obtener las fechas de fin y de registro para un acceso solicitado GESTIONADO en el 102
-- USE ProyFidens;
-- EXEC sp_help 'ProyFidens.dbo.ADM_ACTIVACION_CUENTA';
-- USE master;
-- EXEC dbo.rdu_infraProyFidensSolicitadosRDU 'FIDENSLAT\gchavez', '10.0.0.61', 'RDP', NULL;
-- EXEC dbo.rdu_infraProyFidensSolicitadosRDU '.\hcaycho', '10.0.0.80', 'RDP', NULL;
-- EXEC dbo.rdu_infraProyFidensSolicitadosRDU 'FIDENSLAT\ecordova', '10.0.0.61', 'RDP', NULL;
-- EXEC dbo.rdu_infraProyFidensSolicitadosRDU 'FIDENSLAT\jtoledo', '10.0.0.49', 'RDP', NULL;
-- =============================================
CREATE PROCEDURE dbo.rdu_infraProyFidensSolicitadosRDU
	@User VARCHAR(100),   -- Debe ser UsuarioOriginal FIDENSLAT\mcobos o .\mcobos
	@Serv VARCHAR(100),
	@Grup VARCHAR(3),
	@SubPry INT = NULL
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @fechaFin VARCHAR(25);
	DECLARE @NumReg INT;
	DECLARE @CodUsr VARCHAR(5);
	DECLARE @usrClean VARCHAR(100);
	SET @UsrClean = 
	(
		SELECT CASE 
				WHEN CHARINDEX('\', @user) > 0 
					 THEN RIGHT(@User, CHARINDEX('\', REVERSE(@User)) - 1)
				ELSE @user
			   END
	);
	
	-- PRINT @UsrClean;
	IF (@Grup = 'RDP')
	BEGIN
		SELECT TOP 1 @NumReg = NRO, @fechaFin=FFIN, @CodUsr = COD_USER
		FROM (
			SELECT CTA.AAC_IDENAAC AS NRO, 
				-- CONVERT(VARCHAR(16), CTA.ACC_FECHAFIN, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAFIN, 108) AS FFIN,
				CONVERT(VARCHAR(10), CTA.ACC_FECHAFIN, 120) + ' ' + CTA.ACC_HORAFIN AS FFIN,
				CTA.USU_SEG_FECHAINS AS FREG, 				
				-- CONVERT(VARCHAR(16), CTA.AAC_FECHAINICIO, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAINICIO, 108) AS FINI,
				CONVERT(VARCHAR(10), CTA.AAC_FECHAINICIO, 120) + ' ' + CTA.ACC_HORAINICIO AS FINI,
				CTA.AGE_SEG_CODIGO AS COD_USER, CTA.ESTADO
			FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA
			INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.AGE_SEG_CODIGO=USR.COD_USER AND USR.STATUS=1
			INNER JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE=SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
			WHERE CTA.ACC_FECHAFIN >= CAST(GETDATE() AS date)
				--CTA.AAC_FECHAINICIO = CAST(GETDATE() AS date)
				AND CTA.ESTADO IN (1,2)
				AND CTA.AAC_PERSMISO LIKE '%RDP%'
				AND LOWER(USR.TXT_ACC) = LOWER(@UsrClean)
				AND SRV.ASE_IPPRIVADA = @Serv
		) AS X
		ORDER BY X.FFIN DESC, X.ESTADO ASC;
	END;
	ELSE IF (@Grup = 'SQL')
	BEGIN
		SELECT TOP 1 @NumReg = NRO, @fechaFin=FFIN, @CodUsr = COD_USER
		FROM (
			SELECT CTA.AAC_IDENAAC AS NRO, 
				-- CONVERT(VARCHAR(16), CTA.ACC_FECHAFIN, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAFIN, 108) AS FFIN,
				CONVERT(VARCHAR(10), CTA.ACC_FECHAFIN, 120) + ' ' + CTA.ACC_HORAFIN AS FFIN,
				CTA.USU_SEG_FECHAINS AS FREG, 
				-- CONVERT(VARCHAR(16), CTA.AAC_FECHAINICIO, 120) + ' ' + CONVERT(VARCHAR(5), CTA.ACC_HORAINICIO, 108) AS FINI,
				CONVERT(VARCHAR(10), CTA.AAC_FECHAINICIO, 120) + ' ' + CTA.ACC_HORAINICIO AS FINI,
				CTA.AGE_SEG_CODIGO AS COD_USER, CTA.ESTADO
			FROM ProyFidens.dbo.ADM_ACTIVACION_CUENTA AS CTA
			INNER JOIN ProyFidens.dbo.SYS_ACCOUNT USR ON CTA.AGE_SEG_CODIGO=USR.COD_USER AND USR.STATUS=1
			INNER JOIN ProyFidens.dbo.ADM_SERVIDOR SRV ON CTA.ASE_IDENASE=SRV.ASE_IDENASE AND SRV.ASE_ESTADO=1
			WHERE CTA.ACC_FECHAFIN >= CAST(GETDATE() AS date)
				-- CTA.AAC_FECHAINICIO = CAST(GETDATE() AS date) 
				AND CTA.ESTADO IN (1,2)
				AND CTA.AAC_PERSMISO LIKE '%SQL%'
				AND CTA.ADM_IDPROY = @SubPry
				AND LOWER(USR.TXT_ACC) = LOWER(@UsrClean) 
				AND SRV.ASE_IPPRIVADA = @Serv
		) AS X
		ORDER BY X.FFIN DESC, X.ESTADO ASC;
	END;
    -- RESULTADO FORZADO Y LIMPIO
    SELECT @fechaFin  AS FechaFin,
		CAST(@NumReg AS INT)			AS NumReg,
		@CodUsr							AS CodUser;
END
GO
